### PR TITLE
Update to latest freedesktop sdk

### PR DESCRIPTION
**Pull request by Sunderland93**
Update to Freedesktop SDK 18.08

### CODE REVIEW

**Comment by Sunderland93** [comment]
bot, build

**Comment by Sunderland93** [comment]
bot, build

**Comment by Sunderland93** [comment]
bot, build

**Comment by Sunderland93** [comment]
bot, build

**Comment by Sunderland93** [comment]
bot, build

**Comment by Sunderland93** [comment]
bot, build

**Comment by Sunderland93** [comment]
bot, build

**Comment by alexlarsson** [comment]
I cancelled the build because it had to restart build-bot, but one build had already failed anyway.

**Pull request closed without merging**
