### PR TITLE
Update to SDK 19.08

### LINKED ISSUE #16: Update runtime to 19.08

### PR DESCRIPTION
**Pull request by Sunderland93**
Closes #16

### CODE REVIEW

**Comment by Sunderland93** [comment]
Build fail with `JSON syntax error in the manifest (failure)6 Set flathub properties` @nedrichards can you help?

**Comment by rodlie** [comment]
Validate the json.
```
bad escaped character at line 115 column 42
```

**Comment by Sunderland93** [comment]
@rodlie but it works great on my machine. I didn't change anything in line 115 before

**Comment by rodlie** [comment]
I don't know, but look at the file and you can see the issue:
https://github.com/flathub/fr.natron.Natron/blob/f4d76e84bc7e046f4bce7c531abd0cb34ac2050d/fr.natron.Natron.json#L115

**Pull request merged**
