### PR TITLE
Added librsvg to prevent openfx-arena plugins from segfault

### LINKED ISSUE #12: Updated version does not work.
Hi I updated Natron today and now it has the same problem that the official installer and portable and don't start the program.
```

Load OFX Plugins: scan plugins... 
couldn't open library /app/Plugins/OFX/Natron/Arena.ofx.bundle/Contents/Linux-x86-64/Arena.ofx because /usr/lib/x86_64-linux-gnu/librsvg-2.so.2: undefined symbol: cairo_tag_end
Caught segmentation fault (SIGSEGV) from thread Main(0x55ff6829e610), faulty address is 0x42c00 from 0x42c0
```

### PR DESCRIPTION
**Pull request by Sunderland93**
Fix #12

### CODE REVIEW

**Comment by TingPing** [comment]
Both cairo and librsvg are in the runtime, so you should probably just find out what version fixed your problem and get them to update.

**Comment by Sunderland93** [comment]
Natron did not find cairo from the runtime, so I put it into build recipe.

**Comment by TingPing** [comment]
You should probably find out why instead of just bundling junk.. its all clearly there.

**Comment by Sunderland93** [comment]
It's short-time workaround. I'll find out why Natron did not detect cairo from runtime

**Comment by Sunderland93** [comment]
Same for gdk-pixbuf. I get an error while building openfx-arena plugins with gdk-pixbuf from runtime:
```
/usr/lib/gcc/x86_64-unknown-linux-gnu/8.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lstaticpixbufloader-png
/usr/lib/gcc/x86_64-unknown-linux-gnu/8.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lstaticpixbufloader-jpeg
```

**Pull request merged**
